package openArcanoid;

public enum SoundEffect {
	BLOCKKILL, METALBLOCKHIT, PADHIT, METALBLOCKKILL, FIREBALL, FIRELASER, BUMPBORDER, LASER, SIZEDOWN, SIZEUP, STICKY, TRIPLE, EXTRALIVE, LIVELOST, NEWLEVEL, GAMEOVER, LEVELCLEARED, BREAK, SLOWDOWN;
}
